<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.10.11 on win32)" generated="2025-06-13T16:07:07.500175" rpa="false" schemaversion="5">
<suite id="s1" name="Robot Interactive Console" source="c:\Users\KomsakPanphun\.windsurf\extensions\robocorp.robotframework-lsp-1.13.0-universal\src\robotframework_ls\vendored\robotframework_interactive\robot_interactive_console.robot">
<test id="s1-t1" name="Default Task/Test" line="5">
<kw name="Interpreter Main Loop" owner="MainLoop">
<status status="PASS" start="2025-06-13T16:07:07.539985" elapsed="1.652290"/>
</kw>
<status status="PASS" start="2025-06-13T16:07:07.538998" elapsed="1.653277"/>
</test>
<status status="PASS" start="2025-06-13T16:07:07.503170" elapsed="1.690105"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Robot Interactive Console" id="s1" pass="1" fail="0" skip="0">Robot Interactive Console</stat>
</suite>
</statistics>
<errors>
<msg time="2025-06-13T16:07:07.492047" level="WARN">Error in file 'c:\Users\KomsakPanphun\.windsurf\extensions\robocorp.robotframework-lsp-1.13.0-universal\src\robotframework_ls\vendored\robotframework_interactive\robot_interactive_console.robot' on line 4: Singular section headers like '*** Test Case ***' are deprecated. Use plural format like '*** Test Cases ***' instead.</msg>
</errors>
</robot>
